#!/bin/sh

. .workshop/settings.sh

WORKSHOP_IMAGE=${REGISTRY}/${WORKSHOP_NAME}:${WORKSHOP_VERSION}

docker build -t ${WORKSHOP_NAME}:${WORKSHOP_VERSION} .
docker tag ${WORKSHOP_NAME}:${WORKSHOP_VERSION} ${WORKSHOP_IMAGE}
