apiVersion: sources.knative.dev/v1alpha1
kind: KafkaSource
metadata:
  name: kafka-source
spec:
  consumerGroup: knative-group
  bootstrapServers: knative-cluster-kafka-bootstrap.labs-infra:9092 #note the kafka namespace
  topics: eventing
  sink:
    apiVersion: serving.knative.dev/v1alpha1
    kind: Service
    name: logevents
