apiVersion: v1
kind: ConfigMap
metadata:
  name: customer
data:
  application.properties: |
    com.redhat.developer.demos.customer.rest.PreferenceService/mp-rest/url=http://preference.$NAMESPACE:8080
---
apiVersion: serving.knative.dev/v1alpha1 # Current version of Knative
kind: Service
metadata:
  name: customer
spec:
  template:
    metadata:
      name: customer-v1
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
        - image: quay.io/dsanchor/customer:quarkus
          env:
            - name: VERSION
              value: "v1"
          volumeMounts:
            - name: configuration
              mountPath: /deployments/config
      volumes:
        - name: configuration
          configMap:
            name: customer
