apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: lab-knative-user
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - 'patch'
- apiGroups:
  - "eventing.knative.dev"
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - "rbac.authorization.k8s.io"
  resources:
  - 'clusterroles'
  verbs:
  - '*'
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - "*"