---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: lab-installer
subjects:
- kind: ServiceAccount
  name: lab-installer
  namespace: "{{NAMESPACE}}"
roleRef:
  kind: ClusterRole
  name: lab-installer
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: lab-installer-self-provisioner
subjects:
- kind: ServiceAccount
  name: lab-installer
  namespace: "{{NAMESPACE}}"
roleRef:
  kind: ClusterRole
  name: self-provisioner
  apiGroup: rbac.authorization.k8s.io
#---
#apiVersion: rbac.authorization.k8s.io/v1
#kind: ClusterRoleBinding
#metadata:
#  name: lab-installer-cluster-admin
#subjects:
#- kind: ServiceAccount
#  name: lab-installer
#  namespace: "{{NAMESPACE}}"
#roleRef:
#  apiGroup: rbac.authorization.k8s.io
#  kind: ClusterRole
#  name: cluster-admin
